Preserve timestamps in reject files

diff --git a/tests/reject-format b/tests/reject-format
--- a/tests/reject-format
+++ b/tests/reject-format
@@ -26,7 +26,7 @@ a() {
 EOF
 
 sed -e 's/5/5a/' f.orig > f
-diff -p -c f.orig f > f.diff
+diff -p -c -L f.orig -L f f.orig f > f.diff
 
 check 'patch -f -F0 --no-backup-if-mismatch f < f.diff || echo "Status: $?"' <<EOF
 patching file f
@@ -57,7 +57,7 @@ EOF
 
 # --------------------------------------------------------------
 
-( echo "Index: f"; diff -p -u f.orig f ) > f.diff
+( echo "Index: f"; diff -p -u -L f.orig -L f f.orig f ) > f.diff
 check 'patch -f -F0 --no-backup-if-mismatch f < f.diff || echo "Status: $?"' <<EOF
 patching file f
 Hunk #1 FAILED at 2.
@@ -81,7 +81,7 @@ EOF
 
 # --------------------------------------------------------------
 
-diff -p -c f.orig f > f.diff
+diff -p -c -L f.orig -L f f.orig f > f.diff
 check 'patch -f -F0 --no-backup-if-mismatch --reject-format=unified f < f.diff || echo "Status: $?"' <<EOF
 patching file f
 Hunk #1 FAILED at 2.
@@ -104,7 +104,7 @@ EOF
 
 # --------------------------------------------------------------
 
-( echo "Index: f"; diff -p -u f.orig f ) > f.diff
+( echo "Index: f"; diff -p -u -L f.orig -L f f.orig f ) > f.diff
 check 'patch -f -F0 --no-backup-if-mismatch --reject-format=context f < f.diff || echo "Status: $?"' <<EOF
 patching file f
 Hunk #1 FAILED at 2.
@@ -131,4 +131,26 @@ Index: f
 ! 5a
   6
   }
+EOF
+
+# ==============================================================
+
+echo one > a
+echo two > b
+diff -u -L "a	label of a" -L "b	label of b" a b > ab.diff
+mv b a
+
+check 'patch -f < ab.diff || echo "Status: $?"' <<EOF
+patching file a
+Hunk #1 FAILED at 1.
+1 out of 1 hunk FAILED -- saving rejects to file a.rej
+Status: 1
+EOF
+
+check 'cat a.rej' <<EOF
+--- a	label of a
++++ b	label of b
+@@ -1 +1 @@
+-one
++two
 EOF
